<a href="https://colab.research.google.com/github/alexandrufalk/Background-generator/blob/Layout-page/CenterNet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow.keras.applications import ResNet50
import tensorflow_datasets as tfds


#Download Pascal VOC Dataset

In [ ]:
# Load Pascal VOC 2007 dataset with bounding boxes
dataset, info = tfds.load("voc/2007", split="train+validation", with_info=True)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

#Explore the Dataset

In [3]:
# Check dataset info
print(info)

# Example: Iterate through the dataset
for sample in dataset.take(1):
    image = sample["image"]
    bbox = sample["objects"]["bbox"]
    label = sample["objects"]["label"]
    print(f"Image shape: {image.shape}")
    print(f"Bounding Boxes: {bbox}")
    print(f"Labels: {label}")

tfds.core.DatasetInfo(
    name='voc',
    full_name='voc/2007/4.0.0',
    description="""
    This dataset contains the data from the PASCAL Visual Object Classes Challenge,
    corresponding to the Classification and Detection competitions.
    
    In the Classification competition, the goal is to predict the set of labels
    contained in the image, while in the Detection competition the goal is to
    predict the bounding box and label of each individual object.
    annotations.
    """,
    config_description="""
    This dataset contains the data from the PASCAL Visual Object Classes Challenge
    2007, a.k.a. VOC2007.
    
    A total of 9963 images are included in this dataset, where each image
    contains a set of objects, out of 20 different classes, making a total of
    24640 annotated objects.
    
    """,
    homepage='http://host.robots.ox.ac.uk/pascal/VOC/voc2007/',
    data_dir=PosixGPath('/tmp/tmphgeq_oe3tfds'),
    file_format=tfrecord,
    download_size=868.85 Mi

#Preprocess the Dataset

In [4]:
def preprocess_sample_fixed(sample, max_boxes=100):
    image = tf.image.resize(sample["image"], (512, 512)) / 255.0  # Normalize image
    boxes = sample["objects"]["bbox"]  # [ymin, xmin, ymax, xmax]
    classes = sample["objects"]["label"]

    # Convert to CenterNet format
    center_x = (boxes[:, 1] + boxes[:, 3]) / 2.0  # (xmin + xmax) / 2
    center_y = (boxes[:, 0] + boxes[:, 2]) / 2.0  # (ymin + ymax) / 2
    width = boxes[:, 3] - boxes[:, 1]  # xmax - xmin
    height = boxes[:, 2] - boxes[:, 0]  # ymax - ymin
    centernet_boxes = tf.stack([center_x, center_y, width, height], axis=-1)

    # Pad to fixed size
    padded_boxes = tf.pad(centernet_boxes, [[0, max_boxes - tf.shape(centernet_boxes)[0]], [0, 0]])
    padded_classes = tf.pad(classes, [[0, max_boxes - tf.shape(classes)[0]]])

    return image, {"boxes": padded_boxes, "classes": padded_classes}

train_dataset = dataset.map(lambda x: preprocess_sample_fixed(x)).batch(8).prefetch(tf.data.AUTOTUNE)

In [5]:
for image, targets in train_dataset.take(1):
    print("Boxes shape:", targets["boxes"].shape)
    print("Boxes:", targets["boxes"])

Boxes shape: (8, 100, 4)
Boxes: tf.Tensor(
[[[0.41002572 0.5572917  0.7326478  0.82708335]
  [0.42416453 0.36249998 0.36503854 0.43333334]
  [0.64524424 0.7270833  0.24164528 0.25416666]
  ...
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]]

 [[0.44599998 0.48000002 0.732      0.8106667 ]
  [0.147      0.52133334 0.29       0.43466666]
  [0.         0.         0.         0.        ]
  ...
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]]

 [[0.503      0.63199997 0.994      0.736     ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  ...
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]
  [0.         0.         0.         0.        ]]

 ...

 [[0.177      0.59466666 0.35       0.8106667 ]
  [0.65       0

#Generate Heatmaps

In [6]:
def generate_heatmap(boxes, labels, output_shape=(128, 128), num_classes=20, sigma=2):
    heatmap = tf.zeros([output_shape[0], output_shape[1], num_classes], dtype=tf.float32)

    # Filter out padded boxes
    valid_indices = tf.reduce_any(boxes != 0, axis=-1)  # Identify valid boxes
    valid_boxes = tf.boolean_mask(boxes, valid_indices)
    valid_labels = tf.boolean_mask(labels, valid_indices)

    for box, label in zip(valid_boxes, valid_labels):
        cx, cy, w, h = box  # Unpack box
        grid_x, grid_y = int(cx * output_shape[1]), int(cy * output_shape[0])

        # Draw Gaussian around the center
        for i in range(max(0, grid_x - 2 * sigma), min(output_shape[1], grid_x + 2 * sigma)):
            for j in range(max(0, grid_y - 2 * sigma), min(output_shape[0], grid_y + 2 * sigma)):
                heatmap = tf.tensor_scatter_nd_update(
                    heatmap,
                    indices=[[j, i, label]],
                    updates=[tf.exp(-((i - grid_x) ** 2 + (j - grid_y) ** 2) / (2 * sigma ** 2))]
                )

    return heatmap



In [9]:
import matplotlib.pyplot as plt

def visualize_heatmap(image, heatmap, class_index=None):
    """
    Visualize the heatmap over the image.

    Args:
    - image: The input image (H, W, 3).
    - heatmap: The generated heatmap (H', W', num_classes).
    - class_index: The class channel to visualize (int or None).
      If None, combines all class heatmaps into one.
    """
    # Normalize the image for display
    image = tf.image.resize(image, (512, 512))  # Resize for visualization
    image = tf.clip_by_value(image, 0.0, 1.0)

    # Extract the heatmap for a specific class or combine all channels
    if class_index is not None:
        heatmap = heatmap[..., class_index]
    else:
        heatmap = tf.reduce_max(heatmap, axis=-1)  # Combine all classes

    # Normalize the heatmap
    heatmap = tf.image.resize(heatmap[..., tf.newaxis], (512, 512))  # Resize to image size
    heatmap = tf.squeeze(heatmap)
    heatmap = (heatmap - tf.reduce_min(heatmap)) / (tf.reduce_max(heatmap) - tf.reduce_min(heatmap) + 1e-6)

    # Overlay the heatmap on the image
    plt.figure(figsize=(8, 8))
    plt.imshow(image)
    plt.imshow(heatmap, cmap='jet', alpha=0.5)  # Heatmap with transparency
    plt.colorbar()
    plt.title("Heatmap Overlay")
    plt.axis("off")
    plt.show()

In [ ]:
for image, targets in train_dataset.take(1):
    # Generate heatmap
    heatmap = generate_heatmap(targets["boxes"], targets["classes"])

    # Visualize for class 0 (or combine all classes)
    visualize_heatmap(image[0], heatmap, class_index=0)


#Define the Backbone

In [ ]:
def create_backbone(input_shape=(512, 512, 3)):
    # Use ResNet50 as backbone without top layers, outputting feature maps
    backbone = ResNet50(input_shape=input_shape, include_top=False, weights="imagenet")
    backbone_output = backbone.get_layer("conv4_block6_out").output  # Choose a layer
    model = tf.keras.Model(inputs=backbone.input, outputs=backbone_output)
    return model

#Detection Head
The detection head will predict:

-Heatmap: to identify object centers.

-Offsets: to adjust for downsampling effects.

-Sizes: to predict the width and height of objects.


In [ ]:
def create_detection_head(backbone_output, num_classes):
    # Heatmap head
    heatmap = tf.keras.layers.Conv2D(64, kernel_size=3, padding="same", activation="relu")(backbone_output)
    heatmap = tf.keras.layers.Conv2D(num_classes, kernel_size=1, padding="same", activation="sigmoid", name="heatmap")(heatmap)

    # Offset head
    offset = tf.keras.layers.Conv2D(64, kernel_size=3, padding="same", activation="relu")(backbone_output)
    offset = tf.keras.layers.Conv2D(2, kernel_size=1, padding="same", name="offset")(offset)  # 2 channels for x and y offsets

    # Size head
    size = tf.keras.layers.Conv2D(64, kernel_size=3, padding="same", activation="relu")(backbone_output)
    size = tf.keras.layers.Conv2D(2, kernel_size=1, padding="same", name="size")(size)  # 2 channels for width and height

    return heatmap, offset, size


#Build the Complete CenterNet Model

In [ ]:
def create_centernet(input_shape=(512, 512, 3), num_classes=80):
    inputs = tf.keras.Input(shape=input_shape)
    backbone_output = create_backbone(input_shape)(inputs)
    heatmap, offset, size = create_detection_head(backbone_output, num_classes)
    model = tf.keras.Model(inputs=inputs, outputs=[heatmap, offset, size])
    return model


#Compile the Model

In [ ]:
def focal_loss(gamma=2.0, alpha=0.25):
    def focal_loss_fixed(y_true, y_pred):
        alpha_factor = tf.where(tf.equal(y_true, 1), alpha, 1 - alpha)
        focal_weight = tf.where(tf.equal(y_true, 1), 1 - y_pred, y_pred)
        focal_weight = alpha_factor * tf.pow(focal_weight, gamma)
        bce = tf.keras.losses.binary_crossentropy(y_true, y_pred)
        return focal_weight * bce
    return focal_loss_fixed

def smooth_l1_loss(y_true, y_pred):
    return tf.keras.losses.Huber()(y_true, y_pred)

centernet = create_centernet()
centernet.compile(optimizer='adam',
                  loss={'heatmap': focal_loss(),
                        'offset': smooth_l1_loss,
                        'size': smooth_l1_loss})

#Train the Model

In [ ]:
history = centernet.fit(train_dataset, validation_data=val_dataset, epochs=20)